// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoNipiFW1xs_8eKR1Y1KP_pEMe_DO2Pzo',
    appId: '1:286698664495:web:0076325b400a15f8f60cda',
    messagingSenderId: '286698664495',
    projectId: 'mapsfirebaseapp-3e60b',
    authDomain: 'mapsfirebaseapp-3e60b.firebaseapp.com',
    storageBucket: 'mapsfirebaseapp-3e60b.firebasestorage.app',
    measurementId: 'G-JL3M0RWXG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkhEQEUcL_3p8vpjjQayIkJYJbsZ22Z4',
    appId: '1:286698664495:android:cec466399c9ab7ccf60cda',
    messagingSenderId: '286698664495',
    projectId: 'mapsfirebaseapp-3e60b',
    storageBucket: 'mapsfirebaseapp-3e60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCHEs8jatx4_qS2ebD630_zIjMf0dRkMU',
    appId: '1:286698664495:ios:5b29d9e706e9cbb5f60cda',
    messagingSenderId: '286698664495',
    projectId: 'mapsfirebaseapp-3e60b',
    storageBucket: 'mapsfirebaseapp-3e60b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCHEs8jatx4_qS2ebD630_zIjMf0dRkMU',
    appId: '1:286698664495:ios:5b29d9e706e9cbb5f60cda',
    messagingSenderId: '286698664495',
    projectId: 'mapsfirebaseapp-3e60b',
    storageBucket: 'mapsfirebaseapp-3e60b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoNipiFW1xs_8eKR1Y1KP_pEMe_DO2Pzo',
    appId: '1:286698664495:web:7d9568b160966ef3f60cda',
    messagingSenderId: '286698664495',
    projectId: 'mapsfirebaseapp-3e60b',
    authDomain: 'mapsfirebaseapp-3e60b.firebaseapp.com',
    storageBucket: 'mapsfirebaseapp-3e60b.firebasestorage.app',
    measurementId: 'G-G82FHV3Y9D',
  );
}
